import { Project } from "@/types";

export const IMGS = {
  hero: "/images/hero.jpg",
  who_we_are: "/images/who-we-are-team.jpg",
  rooftop: "/images/banana-island-rooftop-skyline.jpg",
  project1: "/images/project-1.jpg",
  project2: "/images/project-2.jpg",
  project3: "/images/project-3.jpg",
  project4: "/images/project-4.jpg",
  process: "/images/site-qa-surveying.jpg",
  cta: "/images/cta.jpg",
  sec_residential: "/images/project-1.jpg",
  sec_commercial: "/images/project-2.jpg",
  sec_government: "/images/process.jpg",
  sec_healthcare: "/images/project-3.jpg",
  sec_educational: "/images/project-4.jpg",
  sec_industrial: "/images/cta.jpg",
  sec_infra: "/images/project-2.jpg",
  sec_institutional: "/images/project-3.jpg",
} as const;

export const VERIFIED_PROJECTS: Project[] = [
  // Pillar 1: Institutional & National Infrastructure
  {
    slug: "calabar-itu-highway-bridges",
    title: "Calabar–Itu Federal Highway & 4 Major Bridges",
    location: "Cross River & Akwa Ibom States",
    category: "Highway & Bridge Engineering",
    pillar: "infrastructure",
    year: "2020 – 2021",
    image: "/projects/calabar-highway-culvert.jpg",
    client: "Federal Ministry of Works",
    scope: "28.6km dual carriage highway, swamp subgrade stabilization, cut-and-fill, and 4 major reinforced concrete bridges including Atan & Okpokong.",
    description: "Multi-billion Naira federal highway dualization delivering heavy civil excavation, swamp reclamation, and major river crossing bridge structures.",
  },
  {
    slug: "dangote-petroleum-refinery",
    title: "Dangote Petroleum Refinery & Petrochemicals Complex",
    location: "Lekki Free Trade Zone, Lagos State",
    category: "Heavy Industrial Civil Works",
    pillar: "infrastructure",
    year: "2018 – 2020",
    image: "/images/cta.jpg",
    client: "Dangote Oil Refining Company (DORC)",
    scope: "Heavy industrial concrete foundations, administrative building complexes, and high-tolerance technical substructures at the world's largest single-train refinery.",
    description: "Critical civil structures and administrative site infrastructure supporting the continental mega-refinery.",
  },
  {
    slug: "new-massey-street-children-hospital",
    title: "New Massey Street Children’s Hospital",
    location: "Adeniji Adele Road, Lagos Island, Lagos State",
    category: "Healthcare Infrastructure",
    pillar: "infrastructure",
    year: "2021 – 2023",
    image: "/images/project-3.jpg",
    client: "Lagos State Government (Ministry of Health)",
    scope: "7-storey, 150-bed ultra-modern specialist paediatric hospital and emergency healthcare complex on constrained urban island terrain.",
    description: "State-of-the-art tertiary paediatric healthcare facility executed with advanced reinforced concrete framing and tower crane logistics.",
  },
  {
    slug: "cbn-centre-of-excellence-enugu",
    title: "CBN Centre of Excellence Postgraduate Complex",
    location: "University of Nigeria, Enugu Campus (UNEC)",
    category: "Institutional Infrastructure",
    pillar: "infrastructure",
    year: "2019",
    image: "/projects/cbn-centre-enugu.jpg",
    client: "Central Bank of Nigeria (CSR Project)",
    scope: "Postgraduate complex facilities, faculty building substructures, heavy raft foundation rebar matrices, and regional urban storm drainage retaining walls across Uwani and Ogui districts.",
    description: "Landmark educational and research infrastructure at UNEC, engineered with precision optical theodolite leveling, deep reinforced concrete retaining walls, and monolithic foundation rafts.",
  },
  {
    slug: "jos-stadium-regional-infrastructure",
    title: "Jos Stadium & Regional Civil Infrastructure",
    location: "Jos, Plateau State",
    category: "Sports & Urban Infrastructure",
    pillar: "infrastructure",
    year: "2013 – 2015",
    image: "/projects/jos-stadium-works.jpg",
    client: "Plateau State Government",
    scope: "Multi-billion Naira stadium structural works, steel roof grandstand trusses, urban arterial road dualizations, and storm drainage networks.",
    description: "Heavy civic and regional sporting infrastructure engineered for high-density public assembly.",
  },

  // Pillar 2: Ultra-Luxury High-Rise & Island Enclaves
  {
    slug: "the-palisades-banana-island",
    title: "The Palisades Luxury Residences (Plot L1)",
    location: "Plot L1, 401 Close, Banana Island, Ikoyi, Lagos",
    category: "Ultra-Luxury Waterfront High-Rise",
    pillar: "luxury",
    year: "Active Delivery",
    image: "/projects/banana-island-waterfront-aerial.jpg",
    client: "Joe Faraday Limited",
    scope: "Ultra-luxury multi-storey waterfront residential tower, subterranean semi-raft foundations, waterfront retaining walls, and bespoke penthouses.",
    description: "Nigeria's most prestigious waterfront enclave development engineered with marine-grade concrete and deep foundation stability.",
  },
  {
    slug: "the-woodlands-banana-island",
    title: "The Woodlands Luxury Residences",
    location: "102 Close, Banana Island, Ikoyi, Lagos State",
    category: "Ultra-Luxury Residential",
    pillar: "luxury",
    year: "Active Delivery",
    image: "/projects/the-woodlands-banana-island-master.jpg",
    client: "Joe Faraday Limited",
    scope: "Multi-storey bespoke luxury residential apartments, subterranean basements, infinity swimming pool deck, and elite architectural finishes.",
    description: "Architectural masterpiece combining ultra-luxury aesthetic design with rigorous structural engineering.",
  },
  {
    slug: "plot-k14-banana-island-tower",
    title: "Plot K14 14-Storey Mixed-Use Luxury Tower",
    location: "Plot K14, Banana Island Estate, Ikoyi, Lagos",
    category: "High-Rise & Deep Foundation Piling",
    pillar: "luxury",
    year: "2020 – 2022",
    image: "/projects/banana-island-plot-k14-tower.jpg",
    client: "Sermatech Nigeria Limited",
    scope: "14-storey high-rise tower, deep geotechnical piling foundation (50 bored piles, 300KN load capacity, semi-raft foundation).",
    description: "High-rise structural engineering overcoming coastal subsoil conditions through precision foundation piling.",
  },
  {
    slug: "pearl-gardens-megapark-sangotedo",
    title: "Pearl Gardens & Pearl Megapark / Nuga Estates",
    location: "Sangotedo, Lekki Expressway Corridor, Lagos",
    category: "Master-Planned Gated Communities",
    pillar: "luxury",
    year: "2016 – 2018",
    image: "/projects/pearl-gardens-sangotedo-estate.jpg",
    client: "CMB Building-Maintenance & Investment Co. Ltd",
    scope: "Large-scale master-planned residential estates comprising multi-unit detached duplexes, perimeter retaining walls, and paved internal road networks.",
    description: "Master-planned residential living built with integrated drainage and durable road pavements.",
  },

  // Pillar 3: Turnkey Residential & Regional Commercial Builds
  {
    slug: "akure-residential-duplexes",
    title: "Akure Multi-Site Residential Duplexes & Homes",
    location: "Sholagbade Oshinle Street & environs, Akure, Ondo State",
    category: "Turnkey Residential Developments",
    pillar: "turnkey",
    year: "2017 – Present",
    image: "/projects/akure-residential-homes.png",
    client: "Private Property Investors",
    scope: "Multiple residential duplexes, blocks of luxury flats, gated family villas, and turnkey structural delivery from virgin ground to finishes.",
    description: "Flagship private residential developments engineered with zero-defect structural integrity.",
  },
  {
    slug: "ile-oluji-private-residence",
    title: "Ile-Oluji Private Luxury Residence",
    location: "Ile-Oluji, Ondo State",
    category: "Turnkey Residential Build",
    pillar: "turnkey",
    year: "2021 – 2022",
    image: "/images/project-1.jpg",
    client: "Private Client",
    scope: "Complete turnkey architectural and structural residential construction, perimeter compound civil engineering, and luxury finishes.",
    description: "Bespoke private luxury villa engineered from foundation trenching to completed handover.",
  },
  {
    slug: "ibadan-residential-oversight",
    title: "Ibadan Multi-Unit Residential Construction",
    location: "Ibadan, Oyo State",
    category: "Residential Construction & Supervision",
    pillar: "turnkey",
    year: "2019 – 2021",
    image: "/images/project-4.jpg",
    client: "Private Property Owners",
    scope: "Multi-unit residential construction, structural engineering supervision, quality control auditing, and material testing.",
    description: "High-standard residential build executed with rigorous structural oversight and cost accountability.",
  },
  {
    slug: "borno-police-barracks-workshop",
    title: "Police Barracks Technical Workshop Facility",
    location: "Borno State",
    category: "Institutional & Security Infrastructure",
    pillar: "turnkey",
    year: "2013",
    image: "/projects/borno-police-workshop.jpg",
    client: "Nigeria Police Force / Ministry of Police Affairs",
    scope: "Dedicated technical workshop building, heavy maintenance structural facility, and structural steel roof trusses.",
    description: "Heavy institutional engineering ensuring durable operational capacity under demanding conditions.",
  },
  {
    slug: "yobe-educational-facilities-roads",
    title: "Yobe Educational Facilities & Civil Access Roads",
    location: "Damaturu & Environs, Yobe State",
    category: "Educational Infrastructure & Civil Roads",
    pillar: "turnkey",
    year: "2014 – 2015",
    image: "/images/project-2.jpg",
    client: "State Government / Institutional Client",
    scope: "School classroom blocks, administrative centers, reinforced box culverts, and asphaltic civil access roads.",
    description: "Educational civic infrastructure built to withstand severe regional climate extremes.",
  },
  {
    slug: "benue-state-quality-control-lab",
    title: "Benue State Civil Engineering Quality Control Lab",
    location: "Makurdi, Benue State",
    category: "Civil Engineering Testing Facility",
    pillar: "infrastructure",
    year: "2016",
    image: "/images/process.jpg",
    client: "State Institutional Client",
    scope: "Civil engineering materials testing laboratory, concrete cube crushing test beds, and soils compaction testing facility.",
    description: "Specialized geotechnical and structural materials testing facility ensuring compliance across state works.",
  },
];
